# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
# resolver: lts-12.11
# resolver: lts-11.22
resolver: lts-14.2

packages:
- pg-schema
- pg-schema-tutorial
